name: Dockerized Node.js CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: docker build -t backend .

      - name: Run ESLint
        run: docker run --rm backend yarn lint

      - name: Run tests inside container
        env:
          MONGO_URI: ${{ secrets.MONGO_URI_TEST }}
        run: |
          docker run --rm \
            -e NODE_ENV=test \
            -e MONGO_URI=$MONGO_URI \
            backend yarn test
            
      - name: Generate Swagger Docs
        if: always()
        run: docker run --rm backend yarn swagger:generate || echo "Swagger generation skipped"
